kind: Service
apiVersion: v1
metadata:
  name: rhel9
  namespace: ocp-virt-app
spec:
  ports:
  - port: 22
    targetPort: 22
    protocol: TCP
  type: LoadBalancer
  selector:
    vm.kubevirt.io/name: rhel9-server