CREATE USER demo WITH PASSWORD 'demo';
CREATE DATABASE demo;
GRANT ALL PRIVILEGES ON DATABASE demo TO demo;

\c demo
GRANT ALL ON SCHEMA public TO demo;
GRANT USAGE ON SCHEMA public TO demo;
GRANT CREATE ON SCHEMA public TO demo;